name: notes
version: 1.0.0+1
publish_to: none
description: Notes app
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  staggered_grid_view_flutter: ^0.0.4
  intl: ^0.17.0
  focused_menu: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fast_color_picker: ^0.1.1
  flutter_zoom_drawer: ^3.0.3
  search_page: ^2.0.0+1
  deep_collection: ^1.0.2
  flutter_phoenix: ^1.0.0
  flutter_switch: ^0.3.2
  image_picker: ^0.8.5+3


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.2.0 
  hive_generator: ^1.1.3

flutter: 
  uses-material-design: true

